SELECT
    C.CAR_ID,
    C.CAR_TYPE,
    FLOOR(C.DAILY_FEE * 30 * (1 - P.DISCOUNT_RATE / 100)) AS FEE
FROM CAR_RENTAL_COMPANY_CAR C
LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H
    ON C.CAR_ID = H.CAR_ID
    AND H.START_DATE < '2022-12-01'
    AND H.END_DATE > '2022-10-31'
INNER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
    ON C.CAR_TYPE = P.CAR_TYPE
    AND P.DURATION_TYPE LIKE '30%'
WHERE C.CAR_TYPE IN ('세단', 'SUV')
    AND H.HISTORY_ID IS NULL
HAVING FEE BETWEEN 500000 AND 2000000
ORDER BY
    FEE DESC,
    C.CAR_TYPE,
    C.CAR_ID DESC
    
    